upload:
  #path: src/main/resources/static/uploads/
  path: src/main/webapp/uploads/
spring:
  servlet:
    multipart:
      location: C:\Users\marti\IdeaProjects\jpaproject\project\src\main\resources\static\uploads
      max-file-size: 10MB # 최대 파일 크기
      max-request-size: 10MB # 최대 요청 크기
      enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: practice/*

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    url: jdbc:h2:tcp://localhost/~/kdy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
  # show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/, classpath:/uploads/

