google:
  maps:
    api:
      key: AIzaSyC026p5bYXcL407xPnS0-bwp_trmKuAb84

country:
  api :
    key: w/onpWcWwpLmwUkq6/yqyulugmKO3k7KnTMRfy/hQJs/s7GM9dU474qebwH3AoXxdJl3eE7Ar0CmKOiKaZHdcw==

upload:
  #path: src/main/resources/static/uploads/
  path: src/main/webapp/uploads/

spring:
  servlet:
    multipart:
      location: uploads
      max-file-size: 10MB # 최대 파일 크기
      max-request-size: 10MB # 최대 요청 크기
      enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: practice/*

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    url: jdbc:h2:tcp://localhost/~/kim
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE

  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/, classpath:/uploads/

